import { UserProfile } from "./types";

export const profiles: UserProfile[] = [
    {
        id: 1,
        biography: "Aspiring software engineer with a deep appreciation for faith and family values.",
        name: "Ahmed Khan",
        gender: "Male",
        dateOfBirth: "1990-05-15",
        age: 33,
        ethnicity: "Pakistani",
        location: "England",
        willingToRelocate: "Yes",
        legalStatus: "British Citizen",
        height: "5'11",
        build: "Athletic",
        complexion: "Medium",
        appearance: "Modest",
        disabilities: "No",
        education: "Master’s Degree",
        occupation: "Engineer",
        bornMuslim: "Born Muslim",
        religiousPractice: "Always Prays",
        religiousManhaj: "Hanafi",
        sect: "Sunni",
        maritalStatus: "Single",
        children: "No",
        livingArrangements: "With family",
    },
    {
        id: 2,
        biography: "Teacher with a passion for learning and helping others grow.",
        name: "Fatima Ali",
        gender: "Female",
        dateOfBirth: "1992-07-20",
        age: 31,
        ethnicity: "Bangladeshi",
        location: "Wales",
        willingToRelocate: "Maybe",
        legalStatus: "Permanent Resident",
        height: "5'5",
        build: "Slim",
        complexion: "Fair",
        appearance: "Traditional",
        disabilities: "No",
        education: "Bachelor’s Degree",
        occupation: "Teacher",
        bornMuslim: "Born Muslim",
        religiousPractice: "Usually Prays",
        religiousManhaj: "Shafi",
        sect: "Sunni",
        maritalStatus: "Single",
        children: "No",
        livingArrangements: "Independent",
    },
    {
        id: 3,
        biography: "Entrepreneur who values cultural roots and family togetherness.",
        name: "Mohammed Zubair",
        gender: "Male",
        dateOfBirth: "1987-03-12",
        age: 37,
        ethnicity: "Indian",
        location: "Scotland",
        willingToRelocate: "No",
        legalStatus: "Work Visa",
        height: "5'10",
        build: "Average",
        complexion: "Wheatish",
        appearance: "Modern",
        disabilities: "No",
        education: "PhD or Higher",
        occupation: "Business Owner",
        bornMuslim: "Born Muslim",
        religiousPractice: "Sometimes Prays",
        religiousManhaj: "Hanafi",
        sect: "Sunni",
        maritalStatus: "Divorced",
        children: "Yes",
        livingArrangements: "With family",
    },
    {
        id: 4,
        biography: "Medical professional committed to serving humanity and maintaining faith.",
        name: "Ayesha Noor",
        gender: "Female",
        dateOfBirth: "1995-10-05",
        age: 29,
        ethnicity: "Arab",
        location: "Northern Ireland",
        willingToRelocate: "Yes",
        legalStatus: "British Citizen",
        height: "5'6",
        build: "Athletic",
        complexion: "Medium",
        appearance: "Modest",
        disabilities: "No",
        education: "Master’s Degree",
        occupation: "Doctor",
        bornMuslim: "Born Muslim",
        religiousPractice: "Always Prays",
        religiousManhaj: "Maliki",
        sect: "Sunni",
        maritalStatus: "Single",
        children: "No",
        livingArrangements: "Independent",
    },
    {
        id: 5,
        biography: "IT enthusiast who blends modern technology with traditional values.",
        name: "Zainab Ahmed",
        gender: "Female",
        dateOfBirth: "1993-01-17",
        age: 31,
        ethnicity: "Somalian",
        location: "England",
        willingToRelocate: "Maybe",
        legalStatus: "Student Visa",
        height: "5'4",
        build: "Slim",
        complexion: "Dark",
        appearance: "Modern",
        disabilities: "No",
        education: "Bachelor’s Degree",
        occupation: "IT Professional",
        bornMuslim: "Born Muslim",
        religiousPractice: "Usually Prays",
        religiousManhaj: "Hanbali",
        sect: "Sunni",
        maritalStatus: "Single",
        children: "No",
        livingArrangements: "With family",
    },
];

export default profiles;
