import { UserProfile } from './types'; // Adjust the import based on your types file

export const profiles: UserProfile[] = [
    {
        id: 1,
        name: 'Sarah',
        appearance: 'athletic',
        biography: 'Loves hiking and outdoor adventures. Always looking for new ways to challenge myself.',
        build: 'fit',
        dateOfBirth: '1998-05-12',
        education: 'Bachelor\'s Degree in Graphic Design',
        gender: 'female',
        height: '165 cm',
        livingArrangements: 'alone in a cozy apartment',
        occupation: 'graphic designer at a tech company',
        religiousManhaj: 'sunni',
        religiousPractice: 'practicing',
        willingToRelocate: 'yes, for the right opportunity',
    },
    {
        id: 2,
        name: 'Michael',
        appearance: 'average',
        biography: 'Avid reader, coffee enthusiast, and a fan of tech gadgets. I enjoy exploring new software and learning.',
        build: 'average',
        dateOfBirth: '1995-03-22',
        education: 'Master\'s Degree in Computer Science',
        gender: 'male',
        height: '180 cm',
        livingArrangements: 'with family in a large house',
        occupation: 'software engineer specializing in backend development',
        religiousManhaj: 'shia',
        religiousPractice: 'non-practicing, but respectful',
        willingToRelocate: 'no, happy where I am',
    },
    {
        id: 3,
        name: 'Emma',
        appearance: 'slim',
        biography: 'Passionate about art, culture, and history. I enjoy visiting museums and exploring new creative projects.',
        build: 'slim',
        dateOfBirth: '1999-07-15',
        education: 'High School graduate, currently studying Fine Arts',
        gender: 'female',
        height: '160 cm',
        livingArrangements: 'with friends in a shared apartment',
        occupation: 'artist, working primarily with watercolors',
        religiousManhaj: 'sunni',
        religiousPractice: 'occasionally practicing, spiritual',
        willingToRelocate: 'yes, for artistic opportunities',
    },
    {
        id: 4,
        name: 'James',
        appearance: 'muscular',
        biography: 'Fitness trainer and health coach. I believe in a holistic approach to health, combining physical training with mental well-being.',
        build: 'muscular',
        dateOfBirth: '1996-01-30',
        education: 'Associate Degree in Kinesiology',
        gender: 'male',
        height: '175 cm',
        livingArrangements: 'alone in a modern apartment',
        occupation: 'personal trainer at a local gym',
        religiousManhaj: 'sunni',
        religiousPractice: 'practicing, dedicated to daily rituals',
        willingToRelocate: 'yes, for a career growth opportunity',
    },
    {
        id: 5,
        name: 'Olivia',
        appearance: 'curvy',
        biography: 'Loves cooking and trying new recipes. I am always experimenting with new flavors and ingredients to create unique dishes.',
        build: 'curvy',
        dateOfBirth: '1997-09-10',
        education: 'Bachelor\'s Degree in Culinary Arts',
        gender: 'female',
        height: '170 cm',
        livingArrangements: 'with family in a spacious home',
        occupation: 'chef at a fine dining restaurant',
        religiousManhaj: 'shia',
        religiousPractice: 'practicing, focuses on prayer and community events',
        willingToRelocate: 'no, I prefer staying in my hometown',
    },
];
